fail_fast: false


default_language_version:
  python: python3.13.1

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Typos
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.2
    hooks:
      - id: typos
