[project]
name = "custom_forms"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "ruff>=0.7.3",
]