[project]
name = "custom_forms"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "pre-commit>=4.0.1",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.5",
    "ruff>=0.7.3",
]
