name: Automatic Tests On Open PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv venv --python 3.13.1
          source .venv/bin/activate
          uv sync --dev

      - name: Run ruff
        run: |
          source .venv/bin/activate
          ruff check

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          pytest --cov=src -v tests/
