name: Automatic Tests On Open PR

on:
  pull_request:
    types: [opened, reopened]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Prepare env
        run: make dev

      - name: Run ruff
        run: make ruff

      - name: Run tests
        run: make tests
